name: Build and test

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
        
      - name: Build
        run: ./mvnw --batch-mode -DskipTests package
        
      - name: Maven Tests
        run: ./mvnw --batch-mode -Dmaven.test.failure.ignore=true test
        
      - name: ls
        run: tree 
        
      - name: Report
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
